<?php

$sr_projects = array(
	array
	(
		'Code' => '23859',
		'MasterCode' => NULL,
		'Address' => 'Level 5/38 Humphreys Lane, HURSTVILLE, NSW, 2220',
		'ClientRef' => 'SGCH CA Package',
		'Client' => 'St George Community Housing',
		'ContractorRef' => 'SGCH CA Package',
		'Coordinator' => 'Adris Frety',
		'Duration' => '28',
		'Instructions' => NULL,
		'SLA' => NULL,
		'Status' => 'New',
		'SubClient' => NULL,
		'TaskType' => 'Template',
		'Start' => '2013-09-06T00:00:00',
		'StartDate' => NULL,
		'Finish' => '2013-09-06T00:00:00',
		'FinishDate' => NULL,
	),
	array
	(
		'Code' => '84526',
		'MasterCode' => NULL,
		'Address' => '7/15-17 Betts Street, PARRAMATTA, NSW, 2150',
		'ClientRef' => '0046214',
		'Client' => 'St George Community Housing',
		'ContractorRef' => 'SGCH',
		'Coordinator' => 'Adris Frety',
		'Duration' => '8',
		'Instructions' => 'Window glass R2',
		'SLA' => NULL,
		'Status' => 'New',
		'SubClient' => NULL,
		'TaskType' => 'Project',
		'Start' => '2014-11-25T16:34:00',
		'StartDate' => NULL,
		'Finish' => '2014-11-26T16:00:00',
		'FinishDate' => NULL,
	),
	array
	(
		'Code' => '292',
		'MasterCode' => NULL,
		'Address' => '7-9 Devitt Street, BLACKTOWN, NSW, 2148',
		'ClientRef' => 'RN 7019',
		'Client' => 'Evolve Housing',
		'ContractorRef' => NULL,
		'Coordinator' => 'Eva Enwia',
		'Duration' => NULL,
		'Instructions' => 'E2 SUPPLY KEY RN 7019',
		'SLA' => NULL,
		'Status' => 'New',
		'SubClient' => NULL,
		'TaskType' => 'Job',
		'Start' => NULL,
		'StartDate' => NULL,
		'Finish' => '2013-03-28T00:00:00',
		'FinishDate' => NULL,
	),
	array
	(
		'Code' => '22244',
		'MasterCode' => NULL,
		'Address' => 'Henry Dodd House 9-13 Argyle Street, PARRAMATTA, NSW, 2150',
		'ClientRef' => 'EHCAGC1',
		'Client' => 'Evolve Housing',
		'ContractorRef' => 'EHCAGC',
		'Coordinator' => 'Emma Jeffrey',
		'Duration' => '28',
		'Instructions' => NULL,
		'SLA' => NULL,
		'Status' => 'New',
		'SubClient' => NULL,
		'TaskType' => 'Template',
		'Start' => '2013-08-18T00:00:00',
		'StartDate' => '2013-08-18T00:00:00',
		'Finish' => '2013-09-18T00:00:00',
		'FinishDate' => '2013-08-18T00:00:00',
	),
);
